# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b3ca76cedadfde938c9e180c8869c99004a65656afab5447821711132f6406e59c73a6c51ba8cd58f13e16ecd730cfd82269d4e6a9fbcd1da1db46bfa738171

test:
  secret_key_base: c5ebf8fdde44a573d880d1d57112f025eee8bf4cf99a5d1a8b533b5cdad715377d916902bc15b4992cc7d80733756150e006e7869ee91f6ead928a1c7f4cab5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
